name = "Moggilla"
version = "4.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6891a7bb2bff5013ad935b9e37c7787cd6b49a8f4aa2a22946cf4ddca9984a74"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
