name = "Moggilla"
version = "4.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff32fa7749f30a4c3bcd997412d70dd60d9a87f35ff40c8ca343152c327fc7b8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
