naturalSpawnEnabled = true
# Default: 120.0
# Range: 20.0 ~ 1000.0
health = 120.0
# Default: 6.0
# Range: 0.0 ~ 30.0
armor = 6.0
# Default: 0.24
# Range: 0.05 ~ 0.6
movementSpeed = 0.24
# Default: 13.0
# Range: 1.0 ~ 100.0
meleeDamage = 13.0
# Default: 104.0
# Range: 16.0 ~ 256.0
observeRange = 104.0
# Default: 34.0
# Range: 8.0 ~ 96.0
stalkRange = 34.0
# Default: 13.0
# Range: 4.0 ~ 32.0
warningRange = 13.0
# Default: 128.0
# Range: 16.0 ~ 256.0
antiAirRange = 128.0
# Default: 80.0
# Range: 12.0 ~ 192.0
antiAirVerticalRange = 80.0
# Default: 11.0
# Range: 1.0 ~ 100.0
boulderDamage = 11.0
# Default: 2.15
# Range: 0.4 ~ 5.0
boulderVelocity = 2.15
# Default: 0.065
# Range: 0.005 ~ 0.25
boulderGravity = 0.065
# Default: 0.045
# Range: 0.0 ~ 0.5
boulderAccuracy = 0.045
# Default: 60
# Range: 20 ~ 1200
boulderMinCooldown = 60
# Default: 120
# Range: 20 ~ 1200
boulderMaxCooldown = 120
#Allowed Values: NONE, FRAGILE_ONLY, LOCAL_DAMAGE
aircraftDamageMode = "FRAGILE_ONLY"
# Default: 2.0
# Range: 0.0 ~ 4.0
aircraftDamageRadius = 2.0
# Default: 3
# Range: 0 ~ 8
maxAircraftBlocksDamaged = 3
# Default: 192
# Range: 32 ~ 512
territoryRadius = 192
mobGriefingRequired = true
treeBreakingEnabled = true
# Default: 14
# Range: 1 ~ 20
maxTreeBlocksPerSmash = 14
# Default: 45
# Range: 20 ~ 1200
treeSmashMinCooldown = 45
# Default: 80
# Range: 20 ~ 1200
treeSmashMaxCooldown = 80
sableAeronauticsCompatibility = true
targetCreativePlayers = false
debugLogging = false
